import { NgModule } from '@angular/core';
import {
  DxDrawerModule, 
  DxToolbarModule,
  DxBoxModule, DxPopoverModule,
  DxProgressBarModule,
  DxFileUploaderModule, 
  DxPopupModule,
  DxDataGridModule,
  DxFormModule,
  DxButtonModule,
  DxTextBoxModule,
  DxSelectBoxModule,
  DxTextAreaModule,
  DxNumberBoxModule,
  DxAutocompleteModule,
  DxButtonGroupModule,
  DxSwitchModule,
  DxListModule,
  DxDateBoxModule,
  DxTagBoxModule,
  DxDropDownBoxModule,
  DxTabsModule,
  DxTabPanelModule,
  DxCheckBoxModule,
  DxValidatorModule,
  DxAccordionModule,
  DxContextMenuModule,
  DxRadioGroupModule,
  DxLookupModule,
  DxTooltipModule,
  DxSliderModule,
  DxGalleryModule,
  DxLoadPanelModule
} from 'devextreme-angular';



@NgModule({
  declarations: [],
  imports: [ 
  DxDrawerModule, 
  DxToolbarModule,
  DxBoxModule, DxPopoverModule,
  DxProgressBarModule,
  DxFileUploaderModule, 
  DxPopupModule,
  DxFormModule,
  DxButtonModule,
  DxTextBoxModule,
  DxSelectBoxModule,
  DxTextAreaModule,
  DxNumberBoxModule,
  DxAutocompleteModule,
  DxButtonGroupModule,
  DxSwitchModule,
  DxListModule,
  DxDateBoxModule,
  DxTagBoxModule,
  DxDropDownBoxModule,
  DxTabsModule,
  DxTabPanelModule,
  DxCheckBoxModule,
  DxValidatorModule,
  DxAccordionModule,
  DxContextMenuModule,
  DxRadioGroupModule,
  DxLookupModule,
  DxTooltipModule,
  DxSliderModule,
  DxGalleryModule,
  DxLoadPanelModule,
  DxDataGridModule
  ],
  exports: [   
    DxDrawerModule, 
  DxToolbarModule,
  DxBoxModule, DxPopoverModule,
  DxProgressBarModule,
  DxFileUploaderModule, 
  DxPopupModule,
  DxFormModule,
  DxButtonModule,
  DxTextBoxModule,
  DxSelectBoxModule,
  DxTextAreaModule,
  DxNumberBoxModule,
  DxAutocompleteModule,
  DxButtonGroupModule,
  DxSwitchModule,
  DxListModule,
  DxDateBoxModule,
  DxTagBoxModule,
  DxDropDownBoxModule,
  DxTabsModule,
  DxTabPanelModule,
  DxCheckBoxModule,
  DxValidatorModule,
  DxAccordionModule,
  DxContextMenuModule,
  DxRadioGroupModule,
  DxLookupModule,
  DxTooltipModule,
  DxSliderModule,
  DxGalleryModule,
  DxLoadPanelModule,
  DxDataGridModule
  ]
})
export class DevextrmeModule { }
